version: '2.1'
services:

  # grpahene 3

  service_3_a:
    build: service_3_a/.
    volumes:
      - ./service_3_a/src:/project/src
    ports:
      - 9000:5003
    healthcheck:
      test: curl http://0.0.0.0:5003/graphql/ -H "Content-Type:application/json" --data '{"query":"{__schema { types {name} }}"}'
      interval: 1s
      timeout: 10s
      retries: 20

  service_3_b:
    build: service_3_b/.
    volumes:
      - ./service_3_b/src:/project/src
    ports:
      - 9001:3003
    healthcheck:
      test: curl http://0.0.0.0:5003/graphql/ -H "Content-Type:application/json" --data '{"query":"{__schema { types {name} }}"}'
      interval: 1s
      timeout: 10s
      retries: 20

  service_3_c:
    build: service_3_c/.
    volumes:
      - ./service_3_c/src:/project/src
    ports:
      - 9002:3003
    healthcheck:
      test: curl http://0.0.0.0:5003/graphql/ -H "Content-Type:application/json" --data '{"query":"{__schema { types {name} }}"}'
      interval: 1s
      timeout: 10s
      retries: 20

  service_3_d:
    build: service_3_d/.
    volumes:
      - ./service_3_d/src:/project/src
    ports:
      - 9003:3003
    healthcheck:
      test: curl http://0.0.0.0:5003/graphql/ -H "Content-Type:application/json" --data '{"query":"{__schema { types {name} }}"}'
      interval: 1s
      timeout: 10s
      retries: 20

  federation_3:
    build: federation_3/.
    volumes:
      - ./federation_3/src:/project/src
    ports:
      - 3003:3003
    healthcheck:
      test: curl -f http://0.0.0.0:3003/.well-known/apollo/server-health
      interval: 3s
      timeout: 10s
      retries: 5
    depends_on:
      service_3_a:
        condition: service_healthy
      service_3_b:
        condition: service_healthy
      service_3_c:
        condition: service_healthy
      service_3_d:
        condition: service_healthy

  proxy_dep_3:
    image: busybox
    depends_on:
      federation_3:
        condition: service_healthy

  tests_3:
    build: tests/.
    volumes:
      - ./tests:/project/tests
    depends_on:
      - proxy_dep_3



